# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include: [ dev ]
  paths:
    include:
      - 'uni-flow/**'

pool:
  vmImage: ubuntu-latest

variables:
  WORKDIR: 'uni-flow'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
    displayName: 'Use Node.js 20'

  - script: |
      npm ci
    workingDirectory: '$(System.DefaultWorkingDirectory)/$(WORKDIR)'
    displayName: 'Install deps (npm ci)'

  - script: |
      npm run test --if-present
    workingDirectory: '$(System.DefaultWorkingDirectory)/$(WORKDIR)'
    displayName: 'Run tests'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'dist'
      ArtifactName: 'drop'
      publishLocation: 'Container'
    displayName: 'Publish build artifacts'