trigger:
  branches:
    include:
    - features/F108-calendar
  paths:
    include:
    - 'uni-flow/**'

variables:
- name: WORKDIR
  value: 'uni-flow'

stages:
- stage: BuildReact
  displayName: "React.js build"
  pool:
    vmImage: ubuntu-latest
  jobs:
  - job: Build
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '20.x'
      displayName: 'Install Node.js'

    - checkout: self
      persistCredentials: true

    - task: CmdLine@2
      displayName: 'Install and Build'
      inputs:
        script: |
          npm ci
        workingDirectory: '$(System.DefaultWorkingDirectory)/$(WORKDIR)'
    - task: CmdLine@2
      displayName: 'Unit Testings (Calendar and Planner)'
      inputs:
        script: |
          npm run test:ui
        workingDirectory: '$(System.DefaultWorkingDirectory)/$(WORKDIR)'
