trigger:
- dev

stages:
  - stage: BuildReact
    displayName: "React.js build"
    pool:
      vmImage: ubuntu-latest

    jobs:
      - job: Build
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '20.x'
            displayName: 'Install Node.js'
            cwd: uni-flow

          - script: |
              npm install
              npm run build
            displayName: 'Install and Build'
            workingDirectory: uni-flow
    
  - stage: DownloadComponents
    displayName: "Component download"
    pool:
      vmImage: ubuntu-latest

    jobs:
      - job: Download
        steps:
          - task: CmdLine@2
            inputs:
              script: |
                npm install @fullcalendar/core @fullcalendar/daygrid @fullcalendar/timegrid @fullcalendar/list
                npm install --save @fullcalendar/core @fullcalendar/react @fullcalendar/daygrid
                npm install --save @fullcalendar/timegrid @fullcalendar/interaction
            displayName: 'Calendar component download'
            cwd: uni-flow
          
          - task: CmdLine@2
            inputs:
              script: |
                npx shadcn@latest add dialog
            displayName: 'Form component download'
            cwd: uni-flow
      
  - stage: Test
    displayName: "Run Tests"
    pool:
      vmImage: ubuntu-latest

    jobs:
      - job: RunTests
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '20.x'
            displayName: 'Install Node.js'
            cwd: uni-flow
          
          - script: |
              npm run test --if-present
            displayName: 'Run tests'
            workingDirectory: uni-flow
