name: F101.$(Date:yyyyMMdd).$(Rev:r)

trigger:
  branches:
    include: [ main ]
  paths:
    include:
      - uni-flow/**
      - azure-pipelines.f101.yml

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Use Node.js 18'

  - script: npm ci
    workingDirectory: uni-flow
    displayName: 'Install'

  - script: npm run build
    workingDirectory: uni-flow
    displayName: 'Build'